### ISSUE TITLE
Some things

### ISSUE THREAD

**Issue by rubenwardy** [DonBatman/DonBatman.github.io#1]
Hi, noticed somethings whilst checking out your website.

> All our work is free and opensource. Download it, use it, share it or modify it all you want. Just do not use it to make money.

Free and open source means that you can sell it.

> MaxCohen and I are working hard to make **al** the mods great.

Typo

> Rub**a**nwardy wrote a book

Typo

> http://donbatman.github.io/moddingbook.html

Why do you do this?

**Comment by DonBatman** [comment]
I fixed the typos. I am really sorry for spelling your name wrong. 

"Why do you do this?" - Are you referring to me using iframe to display the book? I sent you a pm on the forum on May 13 2015 and asked if it was ok to use iframe to display on my site or if you would rather I use a direct link to your site. I never got a response. I have no problem changing it to what ever you would be ok with.

**Comment by rubenwardy** [comment]
It doesn't matter - I guess it's to show your navigation at the botom.

**Comment by DonBatman** [comment]
Thanks for pointing out the issues. I appreciate it.
